### ISSUE TITLE
Release v2.1.0 with the parallel support

### ISSUE THREAD

**Issue by Cadair** [sunpy/streamtracer#135]
### Provide a general description of the issue or problem.

This is a blocker for the initial release of sunkit-magex
```[tasklist]
### Tasks
- [ ] https://github.com/sunpy/streamtracer/pull/110
- [x] Get PyPI access
- [x] Make a PyPI token
- [x] Do rc and make sure cibuildwheel works properly
- [x] Do conda builds
- [x] Push final tag
- [ ] https://github.com/conda-forge/streamtracer-feedstock/pull/11
```

**Comment by Cadair** [comment]
hey @dstansby would you be able to add me to streamtracer on pypi so that I can do a release? Thanks!

**Comment by dstansby** [comment]
![Screenshot 2024-05-07 at 16 24 56](https://github.com/sunpy/streamtracer/assets/6197628/930a540b-6e48-47d5-867d-e8f55fa2c4b4)

😄

**Comment by dstansby** [comment]
![Screenshot 2024-05-07 at 16 25 29](https://github.com/sunpy/streamtracer/assets/6197628/7ff018ef-2cb9-48e2-8b2a-a7a41c874aff)

👍

**Comment by Cadair** [comment]
Well, I missed that email. Me and emails do not get on.

**Comment by Cadair** [comment]
Thanks, I am in now :)

**Comment by dstansby** [comment]
:shipit:

**Comment by nabobalis** [comment]
> Well, I missed that email. Me and emails do not get on.

Look at your emails
